[package]
name = "actix-petclinic"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
tracing-subscriber = "0.3"
sea-orm = { version = "1.1", features = [
    "sqlx-mysql",
    "runtime-tokio-native-tls",
    "macros",
] }
dotenvy = "0.15"
